//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 25/11/2018 12:35:48 م
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.ModelConfiguration;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Data.Entity.Core;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

namespace ContosoUniversity.DAL.SalesModel
{
    public partial class SalesContext : DbContext
    {
        #region Constructors

        /// <summary>
        /// Initialize a new SalesContext object.
        /// </summary>
        public SalesContext() :
                base(@"name=SalesConnectionString")
        {
            Configure();
        }

        /// <summary>
        /// Initializes a new SalesContext object using the connection string found in the 'SalesContext' section of the application configuration file.
        /// </summary>
        public SalesContext(string nameOrConnectionString) :
                base(nameOrConnectionString)
        {
            Configure();
        }

        /// <summary>
        /// Initialize a new SalesContext object.
        /// </summary>
        public SalesContext(DbConnection existingConnection, bool contextOwnsConnection) :
                base(existingConnection, contextOwnsConnection)
        {
            Configure();
        }

        /// <summary>
        /// Initialize a new SalesContext object.
        /// </summary>
        public SalesContext(ObjectContext objectContext, bool dbContextOwnsObjectContext) :
                base(objectContext, dbContextOwnsObjectContext)
        {
            Configure();
        }

        /// <summary>
        /// Initialize a new SalesContext object.
        /// </summary>
        public SalesContext(string nameOrConnectionString, DbCompiledModel model) :
                base(nameOrConnectionString, model)
        {
            Configure();
        }

        /// <summary>
        /// Initialize a new SalesContext object.
        /// </summary>
        public SalesContext(DbConnection existingConnection, DbCompiledModel model, bool contextOwnsConnection) :
                base(existingConnection, model, contextOwnsConnection)
        {
            Configure();
        }

        private void Configure()
        {
            this.Configuration.AutoDetectChangesEnabled = true;
            this.Configuration.LazyLoadingEnabled = true;
            this.Configuration.ProxyCreationEnabled = true;
            this.Configuration.ValidateOnSaveEnabled = true;
        }

        #endregion

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Configurations.Add(new Mapping.CarConfiguration());
            modelBuilder.Configurations.Add(new Mapping.SUVConfiguration());
            modelBuilder.Configurations.Add(new Mapping.SalonConfiguration());
            modelBuilder.Configurations.Add(new Mapping.StoreConfiguration());
            modelBuilder.Configurations.Add(new Mapping.ItemConfiguration());
            modelBuilder.Configurations.Add(new Mapping.MedicineConfiguration());
            modelBuilder.Configurations.Add(new Mapping.BookConfiguration());
            modelBuilder.Configurations.Add(new Mapping.PublisherConfiguration());
            modelBuilder.Configurations.Add(new Mapping.AuthorConfiguration());
            modelBuilder.Configurations.Add(new Mapping.ItemStoreConfiguration());

            #region Disabled conventions


            #endregion

        }

    
        /// <summary>
        /// There are no comments for Car in the schema.
        /// </summary>
        public virtual DbSet<Car> Cars { get; set; }
    
        /// <summary>
        /// There are no comments for Store in the schema.
        /// </summary>
        public virtual DbSet<Store> Stores { get; set; }
    
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        public virtual DbSet<Item> Items { get; set; }
    
        /// <summary>
        /// There are no comments for Publisher in the schema.
        /// </summary>
        public virtual DbSet<Publisher> Publishers { get; set; }
    
        /// <summary>
        /// There are no comments for Author in the schema.
        /// </summary>
        public virtual DbSet<Author> Authors { get; set; }
    
        /// <summary>
        /// There are no comments for ItemStore in the schema.
        /// </summary>
        public virtual DbSet<ItemStore> ItemStores { get; set; }
    }
}
