//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 25/11/2018 12:35:51 م
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ContosoUniversity.DAL.SalesModel.Dto
{

    [DataContractAttribute(IsReference=true)]
    public partial class BookDto
    {
        #region Constructors
  
        public BookDto() {
        }

        public BookDto(decimal? price, global::System.DateTime? rowVersion, string category, string enDescription, string arDescription, long id, string iSBN, int? publisherId, ContosoUniversity.DAL.SalesModel.BookLangauge langauge, PublisherDto publisher, List<AuthorDto> authors) {

          this.Price = price;
          this.RowVersion = rowVersion;
          this.Category = category;
          this.EnDescription = enDescription;
          this.ArDescription = arDescription;
          this.Id = id;
          this.ISBN = iSBN;
          this.PublisherId = publisherId;
          this.Langauge = langauge;
          this.Publisher = publisher;
          this.Authors = authors;
        }

        #endregion

        #region Properties

        [DataMember]
        public decimal? Price { get; set; }

        [DataMember]
        public global::System.DateTime? RowVersion { get; set; }

        [DataMember]
        public string Category { get; set; }

        [DataMember]
        public string EnDescription { get; set; }

        [DataMember]
        public string ArDescription { get; set; }

        [DataMember]
        public long Id { get; set; }

        [DataMember]
        public string ISBN { get; set; }

        [DataMember]
        public int? PublisherId { get; set; }

        [DataMember]
        public ContosoUniversity.DAL.SalesModel.BookLangauge Langauge { get; set; }

        #endregion

        #region Navigation Properties

        [DataMember]
        public PublisherDto Publisher { get; set; }

        [DataMember]
        public List<AuthorDto> Authors { get; set; }

        #endregion
    }

}
