//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 25/11/2018 12:35:51 م
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ContosoUniversity.DAL.SalesModel.Dto
{

    [DataContractAttribute(IsReference=true)]
    public partial class ItemDto
    {
        #region Constructors
  
        public ItemDto() {
        }

        public ItemDto(long id, string arDescription, string enDescription, string category, global::System.DateTime? rowVersion, decimal? price, List<ItemStoreDto> itemStores) {

          this.Id = id;
          this.ArDescription = arDescription;
          this.EnDescription = enDescription;
          this.Category = category;
          this.RowVersion = rowVersion;
          this.Price = price;
          this.ItemStores = itemStores;
        }

        #endregion

        #region Properties

        [DataMember]
        public long Id { get; set; }

        [DataMember]
        public string ArDescription { get; set; }

        [DataMember]
        public string EnDescription { get; set; }

        [DataMember]
        public string Category { get; set; }

        [DataMember]
        public global::System.DateTime? RowVersion { get; set; }

        [DataMember]
        public decimal? Price { get; set; }

        #endregion

        #region Navigation Properties

        [DataMember]
        public List<ItemStoreDto> ItemStores { get; set; }

        #endregion
    }

}
