//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 25/11/2018 12:35:51 م
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ContosoUniversity.DAL.SalesModel.Dto
{

    [DataContractAttribute(IsReference=true)]
    public partial class ItemStoreDto
    {
        #region Constructors
  
        public ItemStoreDto() {
        }

        public ItemStoreDto(long id, int minLimit, int maxLimit, int quantity, long itemId, int storeId, ItemDto item, StoreDto store) {

          this.Id = id;
          this.MinLimit = minLimit;
          this.MaxLimit = maxLimit;
          this.Quantity = quantity;
          this.ItemId = itemId;
          this.StoreId = storeId;
          this.Item = item;
          this.Store = store;
        }

        #endregion

        #region Properties

        [DataMember]
        public long Id { get; set; }

        [DataMember]
        public int MinLimit { get; set; }

        [DataMember]
        public int MaxLimit { get; set; }

        [DataMember]
        public int Quantity { get; set; }

        [DataMember]
        public long ItemId { get; set; }

        [DataMember]
        public int StoreId { get; set; }

        #endregion

        #region Navigation Properties

        [DataMember]
        public ItemDto Item { get; set; }

        [DataMember]
        public StoreDto Store { get; set; }

        #endregion
    }

}
