//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 25/11/2018 12:35:51 م
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ContosoUniversity.DAL.SalesModel.Dto
{

    [DataContractAttribute(IsReference=true)]
    public partial class MedicineDto
    {
        #region Constructors
  
        public MedicineDto() {
        }

        public MedicineDto(decimal? price, global::System.DateTime? rowVersion, string category, string enDescription, string arDescription, long id, string scentificName, global::System.DateTime expireDate, string medicalGroup, string batchNo) {

          this.Price = price;
          this.RowVersion = rowVersion;
          this.Category = category;
          this.EnDescription = enDescription;
          this.ArDescription = arDescription;
          this.Id = id;
          this.ScentificName = scentificName;
          this.ExpireDate = expireDate;
          this.MedicalGroup = medicalGroup;
          this.BatchNo = batchNo;
        }

        #endregion

        #region Properties

        [DataMember]
        public decimal? Price { get; set; }

        [DataMember]
        public global::System.DateTime? RowVersion { get; set; }

        [DataMember]
        public string Category { get; set; }

        [DataMember]
        public string EnDescription { get; set; }

        [DataMember]
        public string ArDescription { get; set; }

        [DataMember]
        public long Id { get; set; }

        [DataMember]
        public string ScentificName { get; set; }

        [DataMember]
        public global::System.DateTime ExpireDate { get; set; }

        [DataMember]
        public string MedicalGroup { get; set; }

        [DataMember]
        public string BatchNo { get; set; }

        #endregion
    }

}
