//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 25/11/2018 12:35:51 م
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ContosoUniversity.DAL.SalesModel.Dto
{

    [DataContractAttribute(IsReference=true)]
    public partial class PublisherDto
    {
        #region Constructors
  
        public PublisherDto() {
        }

        public PublisherDto(int id, string name, List<BookDto> books) {

          this.Id = id;
          this.Name = name;
          this.Books = books;
        }

        #endregion

        #region Properties

        [DataMember]
        public int Id { get; set; }

        [DataMember]
        public string Name { get; set; }

        #endregion

        #region Navigation Properties

        [DataMember]
        public List<BookDto> Books { get; set; }

        #endregion
    }

}
