//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 25/11/2018 12:35:51 م
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ContosoUniversity.DAL.SalesModel.Dto
{

    [DataContractAttribute(IsReference=true)]
    public partial class StoreDto
    {
        #region Constructors
  
        public StoreDto() {
        }

        public StoreDto(string name, int id, bool? active, List<ItemStoreDto> itemStores) {

          this.Name = name;
          this.Id = id;
          this.Active = active;
          this.ItemStores = itemStores;
        }

        #endregion

        #region Properties

        [DataMember]
        public string Name { get; set; }

        [DataMember]
        public int Id { get; set; }

        [DataMember]
        public bool? Active { get; set; }

        #endregion

        #region Navigation Properties

        [DataMember]
        public List<ItemStoreDto> ItemStores { get; set; }

        #endregion
    }

}
