//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 25/11/2018 12:35:51 م
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ContosoUniversity.DAL.SalesModel.Dto
{

    [DataContractAttribute(IsReference=true)]
    public partial class SUVDto
    {
        #region Constructors
  
        public SUVDto() {
        }

        public SUVDto(string modelName, int? brandId, int? manufactureYear, int id, int suvType) {

          this.ModelName = modelName;
          this.BrandId = brandId;
          this.ManufactureYear = manufactureYear;
          this.Id = id;
          this.SuvType = suvType;
        }

        #endregion

        #region Properties

        [DataMember]
        public string ModelName { get; set; }

        [DataMember]
        public int? BrandId { get; set; }

        [DataMember]
        public int? ManufactureYear { get; set; }

        [DataMember]
        public int Id { get; set; }

        [DataMember]
        public int SuvType { get; set; }

        #endregion
    }

}
