//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 25/11/2018 12:35:48 م
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data.Entity.ModelConfiguration;

namespace ContosoUniversity.DAL.SalesModel.Mapping
{

    public partial class AuthorConfiguration : EntityTypeConfiguration<Author>
    {

        public AuthorConfiguration()
        {
            this
                .HasKey(p => p.Id)
                .ToTable("Author", "dbo");
            // Properties:
            this
                .Property(p => p.Id)
                    .IsRequired()
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None)
                    .HasColumnType("int");
            this
                .Property(p => p.Name)
                    .IsRequired()
                    .HasColumnType("varchar");
            // Association:
            this
                .HasMany(p => p.Books)
                    .WithMany(c => c.Authors)
                .Map(manyToMany => manyToMany
                    .ToTable("Authors_Books", "dbo")
                    .MapLeftKey("AuthorId")
                    .MapRightKey("ItemId"));
            OnCreated();
        }

        partial void OnCreated();

    }
}
