//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 25/11/2018 12:35:48 م
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data.Entity.ModelConfiguration;

namespace ContosoUniversity.DAL.SalesModel.Mapping
{

    public partial class BookConfiguration : EntityTypeConfiguration<Book>
    {

        public BookConfiguration()
        {
            this
                // Table Per Type (TPT) inheritance child class
                .ToTable("Book", "dbo");
            // Properties:
            this
                .Property(p => p.ISBN)
                    .IsRequired()
                    .HasMaxLength(12)
                    .HasColumnType("varchar");
            this
                .Property(p => p.PublisherId)
                    .HasColumnType("int");
            this
                .Property(p => p.Langauge)
                    .IsRequired()
                    .HasColumnType("int");
            OnCreated();
        }

        partial void OnCreated();

    }
}
