//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 25/11/2018 12:35:48 م
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data.Entity.ModelConfiguration;

namespace ContosoUniversity.DAL.SalesModel.Mapping
{

    public partial class CarConfiguration : EntityTypeConfiguration<Car>
    {

        public CarConfiguration()
        {
            this
                .HasKey(p => p.Id)
                .Map(tpc => { });
            // Properties:
            this
                .Property(p => p.Id)
                    .IsRequired()
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            this
                .Property(p => p.ModelName)
                    .IsUnicode(false);
            OnCreated();
        }

        partial void OnCreated();

    }
}
