//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 25/11/2018 12:35:48 م
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data.Entity.ModelConfiguration;

namespace ContosoUniversity.DAL.SalesModel.Mapping
{

    public partial class ItemStoreConfiguration : EntityTypeConfiguration<ItemStore>
    {

        public ItemStoreConfiguration()
        {
            this
                .HasKey(p => p.Id)
                .ToTable("ItemStores", "dbo");
            // Properties:
            this
                .Property(p => p.Id)
                    .IsRequired()
                    .HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)
                    .HasColumnType("numeric");
            this
                .Property(p => p.MinLimit)
                    .IsRequired()
                    .HasColumnType("int");
            this
                .Property(p => p.MaxLimit)
                    .IsRequired()
                    .HasColumnType("int");
            this
                .Property(p => p.Quantity)
                    .IsRequired()
                    .HasColumnType("int");
            this
                .Property(p => p.ItemId)
                    .IsRequired()
                    .HasColumnType("numeric");
            this
                .Property(p => p.StoreId)
                    .IsRequired()
                    .HasColumnType("int");
            OnCreated();
        }

        partial void OnCreated();

    }
}
