//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 25/11/2018 12:35:48 م
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data.Entity.ModelConfiguration;

namespace ContosoUniversity.DAL.SalesModel.Mapping
{

    public partial class SalonConfiguration : EntityTypeConfiguration<Salon>
    {

        public SalonConfiguration()
        {
            this
                .Map(tpc => {
                    tpc.MapInheritedProperties();
                    tpc.ToTable("Salon", "dbo");
                });
            this
                .Property(p => p.description)
                    .HasColumnName(@"Description");
            // Properties:
            this
                .Property(p => p.SalonType)
                    .HasColumnType("int");
            this
                .Property(p => p.description)
                    .HasColumnName(@"Description")
                    .HasColumnType("varchar");
            OnCreated();
        }

        partial void OnCreated();

    }
}
