//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 25/11/2018 12:35:48 م
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data.Entity.ModelConfiguration;

namespace ContosoUniversity.DAL.SalesModel.Mapping
{

    public partial class SUVConfiguration : EntityTypeConfiguration<SUV>
    {

        public SUVConfiguration()
        {
            this
                .Map(tpc => {
                    tpc.MapInheritedProperties();
                    tpc.ToTable("SUV", "dbo");
                });
            // Property:
            this
                .Property(p => p.SuvType)
                    .IsRequired()
                    .HasColumnType("int");
            OnCreated();
        }

        partial void OnCreated();

    }
}
