//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 25/11/2018 12:35:51 م
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace ContosoUniversity.DAL.SalesModel.Dto
{

    public static partial class BookConverter
    {

        public static BookDto ToDto(this ContosoUniversity.DAL.SalesModel.Book source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static BookDto ToDtoWithRelated(this ContosoUniversity.DAL.SalesModel.Book source, int level)
        {
            if (source == null)
              return null;

            var target = new BookDto();

            // Properties
            target.Price = source.Price;
            target.RowVersion = source.RowVersion;
            target.Category = source.Category;
            target.EnDescription = source.EnDescription;
            target.ArDescription = source.ArDescription;
            target.Id = source.Id;
            target.ISBN = source.ISBN;
            target.PublisherId = source.PublisherId;
            target.Langauge = source.Langauge;

            // Navigation Properties
            if (level > 0) {
              target.Publisher = source.Publisher.ToDtoWithRelated(level - 1);
              target.Authors = source.Authors.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static ContosoUniversity.DAL.SalesModel.Book ToEntity(this BookDto source)
        {
            if (source == null)
              return null;

            var target = new ContosoUniversity.DAL.SalesModel.Book();

            // Properties
            target.Price = source.Price;
            target.RowVersion = source.RowVersion;
            target.Category = source.Category;
            target.EnDescription = source.EnDescription;
            target.ArDescription = source.ArDescription;
            target.Id = source.Id;
            target.ISBN = source.ISBN;
            target.PublisherId = source.PublisherId;
            target.Langauge = source.Langauge;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<BookDto> ToDtos(this IEnumerable<ContosoUniversity.DAL.SalesModel.Book> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<BookDto> ToDtosWithRelated(this IEnumerable<ContosoUniversity.DAL.SalesModel.Book> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<ContosoUniversity.DAL.SalesModel.Book> ToEntities(this IEnumerable<BookDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(ContosoUniversity.DAL.SalesModel.Book source, BookDto target);

        static partial void OnEntityCreating(BookDto source, ContosoUniversity.DAL.SalesModel.Book target);

    }

}
