//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 25/11/2018 12:35:51 م
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace ContosoUniversity.DAL.SalesModel.Dto
{

    public static partial class ItemConverter
    {

        public static ItemDto ToDto(this ContosoUniversity.DAL.SalesModel.Item source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static ItemDto ToDtoWithRelated(this ContosoUniversity.DAL.SalesModel.Item source, int level)
        {
            if (source == null)
              return null;

            var target = new ItemDto();

            // Properties
            target.Id = source.Id;
            target.ArDescription = source.ArDescription;
            target.EnDescription = source.EnDescription;
            target.Category = source.Category;
            target.RowVersion = source.RowVersion;
            target.Price = source.Price;

            // Navigation Properties
            if (level > 0) {
              target.ItemStores = source.ItemStores.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static ContosoUniversity.DAL.SalesModel.Item ToEntity(this ItemDto source)
        {
            if (source == null)
              return null;

            var target = new ContosoUniversity.DAL.SalesModel.Item();

            // Properties
            target.Id = source.Id;
            target.ArDescription = source.ArDescription;
            target.EnDescription = source.EnDescription;
            target.Category = source.Category;
            target.RowVersion = source.RowVersion;
            target.Price = source.Price;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<ItemDto> ToDtos(this IEnumerable<ContosoUniversity.DAL.SalesModel.Item> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<ItemDto> ToDtosWithRelated(this IEnumerable<ContosoUniversity.DAL.SalesModel.Item> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<ContosoUniversity.DAL.SalesModel.Item> ToEntities(this IEnumerable<ItemDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(ContosoUniversity.DAL.SalesModel.Item source, ItemDto target);

        static partial void OnEntityCreating(ItemDto source, ContosoUniversity.DAL.SalesModel.Item target);

    }

}
