//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 25/11/2018 12:35:51 م
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace ContosoUniversity.DAL.SalesModel.Dto
{

    public static partial class SalonConverter
    {

        public static SalonDto ToDto(this ContosoUniversity.DAL.SalesModel.Salon source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static SalonDto ToDtoWithRelated(this ContosoUniversity.DAL.SalesModel.Salon source, int level)
        {
            if (source == null)
              return null;

            var target = new SalonDto();

            // Properties
            target.ModelName = source.ModelName;
            target.BrandId = source.BrandId;
            target.ManufactureYear = source.ManufactureYear;
            target.Id = source.Id;
            target.SalonType = source.SalonType;
            target.description = source.description;

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static ContosoUniversity.DAL.SalesModel.Salon ToEntity(this SalonDto source)
        {
            if (source == null)
              return null;

            var target = new ContosoUniversity.DAL.SalesModel.Salon();

            // Properties
            target.ModelName = source.ModelName;
            target.BrandId = source.BrandId;
            target.ManufactureYear = source.ManufactureYear;
            target.Id = source.Id;
            target.SalonType = source.SalonType;
            target.description = source.description;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<SalonDto> ToDtos(this IEnumerable<ContosoUniversity.DAL.SalesModel.Salon> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<SalonDto> ToDtosWithRelated(this IEnumerable<ContosoUniversity.DAL.SalesModel.Salon> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<ContosoUniversity.DAL.SalesModel.Salon> ToEntities(this IEnumerable<SalonDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(ContosoUniversity.DAL.SalesModel.Salon source, SalonDto target);

        static partial void OnEntityCreating(SalonDto source, ContosoUniversity.DAL.SalesModel.Salon target);

    }

}
