//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 25/11/2018 12:35:51 م
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace ContosoUniversity.DAL.SalesModel.Dto
{

    public static partial class StoreConverter
    {

        public static StoreDto ToDto(this ContosoUniversity.DAL.SalesModel.Store source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static StoreDto ToDtoWithRelated(this ContosoUniversity.DAL.SalesModel.Store source, int level)
        {
            if (source == null)
              return null;

            var target = new StoreDto();

            // Properties
            target.Name = source.Name;
            target.Id = source.Id;
            target.Active = source.Active;

            // Navigation Properties
            if (level > 0) {
              target.ItemStores = source.ItemStores.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static ContosoUniversity.DAL.SalesModel.Store ToEntity(this StoreDto source)
        {
            if (source == null)
              return null;

            var target = new ContosoUniversity.DAL.SalesModel.Store();

            // Properties
            target.Name = source.Name;
            target.Id = source.Id;
            target.Active = source.Active;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<StoreDto> ToDtos(this IEnumerable<ContosoUniversity.DAL.SalesModel.Store> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<StoreDto> ToDtosWithRelated(this IEnumerable<ContosoUniversity.DAL.SalesModel.Store> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<ContosoUniversity.DAL.SalesModel.Store> ToEntities(this IEnumerable<StoreDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(ContosoUniversity.DAL.SalesModel.Store source, StoreDto target);

        static partial void OnEntityCreating(StoreDto source, ContosoUniversity.DAL.SalesModel.Store target);

    }

}
