//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 25/11/2018 12:35:51 م
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace ContosoUniversity.DAL.SalesModel.Dto
{

    public static partial class SUVConverter
    {

        public static SUVDto ToDto(this ContosoUniversity.DAL.SalesModel.SUV source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static SUVDto ToDtoWithRelated(this ContosoUniversity.DAL.SalesModel.SUV source, int level)
        {
            if (source == null)
              return null;

            var target = new SUVDto();

            // Properties
            target.ModelName = source.ModelName;
            target.BrandId = source.BrandId;
            target.ManufactureYear = source.ManufactureYear;
            target.Id = source.Id;
            target.SuvType = source.SuvType;

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static ContosoUniversity.DAL.SalesModel.SUV ToEntity(this SUVDto source)
        {
            if (source == null)
              return null;

            var target = new ContosoUniversity.DAL.SalesModel.SUV();

            // Properties
            target.ModelName = source.ModelName;
            target.BrandId = source.BrandId;
            target.ManufactureYear = source.ManufactureYear;
            target.Id = source.Id;
            target.SuvType = source.SuvType;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<SUVDto> ToDtos(this IEnumerable<ContosoUniversity.DAL.SalesModel.SUV> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<SUVDto> ToDtosWithRelated(this IEnumerable<ContosoUniversity.DAL.SalesModel.SUV> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<ContosoUniversity.DAL.SalesModel.SUV> ToEntities(this IEnumerable<SUVDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(ContosoUniversity.DAL.SalesModel.SUV source, SUVDto target);

        static partial void OnEntityCreating(SUVDto source, ContosoUniversity.DAL.SalesModel.SUV target);

    }

}
