//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 25/11/2018 12:35:48 م
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace ContosoUniversity.DAL.SalesModel
{

    /// <summary>
    /// There are no comments for ContosoUniversity.DAL.SalesModel.Book in the schema.
    /// </summary>
    public partial class Book : Item    {

        public Book()
        {
            OnCreated();
        }


        #region Properties
    
        /// <summary>
        /// There are no comments for ISBN in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(12)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string ISBN
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PublisherId in the schema.
        /// </summary>
        public virtual int? PublisherId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Langauge in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual BookLangauge Langauge
        {
            get;
            set;
        }


        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// There are no comments for Publisher in the schema.
        /// </summary>
        public virtual Publisher Publisher
        {
            get;
            set;
        }
    
        /// <summary>
        /// There are no comments for Authors in the schema.
        /// </summary>
        public virtual ICollection<Author> Authors
        {
            get;
            set;
        }

        #endregion
    
        #region Extensibility Method Definitions
        partial void OnCreated();
        #endregion
    }

}
