//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 25/11/2018 12:35:48 م
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace ContosoUniversity.DAL.SalesModel
{

    /// <summary>
    /// There are no comments for ContosoUniversity.DAL.SalesModel.BookLangauge in the schema.
    /// </summary>
    public enum BookLangauge : int
    {
    
        /// <summary>
        /// There are no comments for BookLangauge.Arabic in the schema.
        /// </summary>
        Arabic = 1,    
        /// <summary>
        /// There are no comments for BookLangauge.English in the schema.
        /// </summary>
        English = 2,    
        /// <summary>
        /// There are no comments for BookLangauge.Frensh in the schema.
        /// </summary>
        Frensh = 3
    }

}
